### PR TITLE
Add --output-find-links options

### PR DESCRIPTION
**Pull request by ropez**
This options is very similar to the existing --output-index-url option.
However, in our case we have a webserver with only a few additional
packages, and we don't mirror all the packages that we need from pypi.
In this case, we need to add a --find-index options to the requirements
file, not a --index-url.

### CODE REVIEW

**Comment by flupke** [comment]
I am so sorry I completely missed your PR.

I solved some conflicts, can you check it still works please?

**Comment by ropez** [comment]
Thanks, I will look into it.

BTW, I'm curious, how did you manage to push to my fork? Are you allowed to do that because I made a pull request?

**Comment by flupke** [comment]
Github magic, I used the web editor :)

**Comment by flupke** [comment]
Tell me if you need a pypi release.

**Pull request merged**
